<?php
// REMOVED: Header is now included by index.php before this file
// include __DIR__ . '/layouts/header.php';

// REMOVED: Session error check is no longer needed here
// if (isset($_SESSION['login_error'])) {
//     $login_error_message = $_SESSION['login_error'];
//     unset($_SESSION['login_error']);
// }
?>
<!DOCTYPE html>
<html lang="uk">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Зручний інтерфейс для роботи з даними.">
    <title>Students</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="public/styles/header.css">
    <link rel="stylesheet" href="public/styles/navigation.css">
    <link rel="stylesheet" href="public/styles/table.css">
    <link rel="stylesheet" href="public/styles/studentsMain.css">
    <link rel="stylesheet" href="public/styles/modal.css">

    <link rel="manifest" href="public/manifest.json">

    <!-- <script>
        if ('serviceWorker' in navigator) {
                window.addEventListener('load', () => {
                    navigator.serviceWorker.register('public/service-worker.js')
                        .then((registration) => {
                            console.log('Service Worker зареєстровано:', registration);
                        })
                        .catch((error) => {
                            console.log('Помилка реєстрації Service Worker:', error);
                        });
                });
            }
    </script> -->
</head>

<body>
    <a class="skipmain" href="#header" target="_self">
        <h1>Student Managment</h1>
    </a>

    <main>
        <button class="burger-menu" id="burger-menu">
            <span class="material-icons">menu</span>
        </button>

        <aside>
            <nav class="sidebar">
                <!-- UPDATED: Use absolute paths with query parameters -->
                <a href="/studentApp/index.php?page=dashboard" id="dashboard-link">Dashboard</a>
                <a href="/studentApp/index.php?page=student" id="students-link">Students</a>
                <a href="/studentApp/index.php?page=tasks" id="tasks-link">Tasks</a>
            </nav>
        </aside>

        <section class="content">
            <div class="content-header">
                <h2>Students</h2>
                <button id="add-btn" class="add-btn">+</button>
            </div>

            <div class="table-container">
                <table id="students-table" class="students-table">
                    <thead>
                        <tr>
                            <th scope="col">
                                <span class="visually-hidden">Select All</span>
                                <input aria-label="select-all" type="checkbox" id="select-all">
                            </th>
                            <th>Group</th>
                            <th>Name</th>
                            <th>Gender</th>
                            <th>Birthday</th>
                            <th>Status</th>
                            <th>Options</th>
                        </tr>
                    </thead>
                    <tbody>
                        <!-- Static rows removed - table body will be populated by JS -->
                    </tbody>
                </table>
            </div>

            <div class="pagination-container">
                <!-- Static buttons removed - Pagination will be generated by studentsMain.js -->
            </div>
        </section>
    </main>

    <div id="modal-overlay" class="modal-overlay"></div>

    <div id="student-modal" class="modal">
        <div class="modal-content">
            <div class="modal-header">
                <h2>Add student</h2>
                <span class="close" id="close-btn">&times;</span>
            </div>
            <div class="modal-body">
                <form id="student-form" novalidate>
                    <div class="form-field">
                        <label for="student-group">Group</label>
                        <select id="student-group" name="student-group">
                            <option value="">Select Group</option>
                            <option value="PZ-21">PZ-21</option>
                            <option value="PZ-22">PZ-22</option>
                            <option value="PZ-23">PZ-23</option>
                            <option value="PZ-24">PZ-24</option>
                            <option value="PZ-25">PZ-25</option>
                            <option value="PZ-26">PZ-26</option>
                            <option value="PZ-27">PZ-27</option>
                        </select>
                    </div>

                    <div class="form-field">
                        <label for="first-name">First name</label>
                        <input type="text" id="first-name" name="first-name" aria-label="first-name">
                    </div>

                    <div class="form-field">
                        <label for="last-name">Last name</label>
                        <input type="text" id="last-name" name="last-name" aria-label="last-name">
                    </div>

                    <div class="form-field">
                        <label for="gender">Gender</label>
                        <select id="gender" name="gender">
                            <option value="">Select Gender</option>
                            <option value="Male">Male</option>
                            <option value="Female">Female</option>
                        </select>
                    </div>

                    <div class="form-field">
                        <label for="birthday">Birthday</label>
                        <input type="date" id="birthday" name="birthday" aria-label="date-name">
                    </div>

                    <div class="validation-options">
                        <div class="validation-method">
                            <p>Validation method:</p>
                            <div>
                                <input type="radio" id="html-validation" name="validation-method" value="html">
                                <label for="html-validation">HTML5</label>
                            </div>
                            <div>
                                <input type="radio" id="js-validation" name="validation-method" value="javascript" checked>
                                <label for="js-validation">JavaScript</label>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button class="cancel-btn" id="cancel-btn">Cancel</button>
                <button class="create-btn" id="create-btn">Create</button>
            </div>
        </div>
    </div>

    <div id="delete-modal" class="modal">
        <div class="modal-content">
            <div class="modal-header">
                <h2>Confirm Deletion</h2>
                <span class="close" id="delete-close-btn">&times;</span>
            </div>
            <div class="modal-body">
                <p id="delete-message"></p>
            </div>
            <div class="modal-footer">
                <button id="delete-cancel-btn" class="cancel-btn">Cancel</button>
                <button id="delete-confirm-btn" class="create-btn">OK</button>
            </div>
        </div>
    </div>

    <!-- REMOVED: Duplicate Login Modal Block -->
    <!-- <div id="loginModal" class="modal"> ... </div> -->

    <!-- Include JS files at the end -->
    <!-- UPDATED: Use absolute paths for JS files for consistency -->
    <script src="/studentApp/public/scripts/header.js"></script>
    <script src="/studentApp/public/scripts/navigation.js"></script>
    <script src="/studentApp/public/scripts/validation.js"></script>
    <script src="/studentApp/public/scripts/studentsMain.js"></script>

    <!-- ADDED: JavaScript to check for login error parameter -->
    <script>
        document.addEventListener('DOMContentLoaded', () => {
            const urlParams = new URLSearchParams(window.location.search);
            if (urlParams.has('login_error')) {
                alert('Invalid username or password.');
                // Clean the URL to remove the error parameter
                const newUrl = window.location.pathname + window.location.search.replace(/[\?&]login_error=1/, '').replace(/^&/, '?');
                window.history.replaceState({}, document.title, newUrl);
            }
        });
    </script>
</body>

</html>